apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: default
spec:
  replicas: 6
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: 3.109.184.36:31503/docker-repo-bank/webapp:21
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service   
metadata:
  name: webapp-svc
  namespace: default
spec:
  selector: 
    app: webapp
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 32081         
  type: NodePort
